apiVersion: apps/v1
kind: Deployment
metadata:
  name: marlinerino
  namespace: marlinerino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marlinerino
  template:
    metadata:
      labels:
        app: marlinerino
    spec:
      containers:
        - name: marlinerino
          image: IMAGE_REPLACE
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: marlinerino-loadbalancer
  namespace: marlinerino
spec:
  type: LoadBalancer
  selector:
    app: marlinerino
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
