name: Deploy nginx to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy marlinerino
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${GITHUB_SHA::8}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull, tag & push marlinerino:latest
        run: |
          docker pull nginx:latest
          docker tag nginx:latest ${{ secrets.DOCKERHUB_USERNAME }}/marlinerino:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/marlinerino:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.AWS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Replace image placeholder in Deployment manifest
        run: sed -i "s|IMAGE_REPLACE|${{ secrets.DOCKERHUB_USERNAME }}/marlinerino:${{ env.IMAGE_TAG }}|g" manifests/marlinerino.yaml

      - name: Apply Deployment and Service
        run: kubectl apply -f manifests/marlinerino.yaml
